- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Install gnupg and apt-transport-https
  apt:
    name:
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Logstash
  apt:
    name: logstash
    state: present
    update_cache: yes

- name: Copy Logstash pipeline
  template:
    src: apache.conf.j2
    dest: "/etc/logstash/conf.d/{{ logstash_pipeline_config }}"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Enable and start Logstash
  systemd:
    name: logstash
    enabled: yes
    state: started
