- name: Download Filebeat 7.17.29
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.29-amd64.deb
    dest: /tmp/filebeat.deb

- name: Install Filebeat
  apt:
    deb: /tmp/filebeat.deb

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Enable Apache and System modules
  shell: |
    filebeat modules enable system
    filebeat modules enable apache
  args:
    creates: /etc/filebeat/modules.d/apache.yml
  notify: restart filebeat

- name: Ensure Filebeat is enabled and started
  systemd:
    name: filebeat
    enabled: yes
    state: started