- name: Download Filebeat 8.x
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.14.0-amd64.deb
    dest: /tmp/filebeat.deb

- name: Install Filebeat
  apt:
    deb: /tmp/filebeat.deb

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644

- name: Enable Apache and System modules
  shell: |
    filebeat modules enable system
    filebeat modules enable apache
  args:
    creates: /etc/filebeat/modules.d/apache.yml

- name: Restart Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
