- name: Ensure gnupg is installed (required for apt_key)
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Download Kibana 7.17.29 Debian package
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-7.17.29-amd64.deb
    dest: /tmp/kibana-7.17.29-amd64.deb
    mode: '0644'

- name: Install Kibana 7.17.29 package
  apt:
    deb: /tmp/kibana-7.17.29-amd64.deb
    state: present

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
